const REGISTER = "REGISTER";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const GET_USERNAME = "GET_USERNAME";
 
const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
const GET_CHATS = "GET_CHATS";
const ADD_CHAT = "ADD_CHAT";

const GET_MESSAGES = "GET_MESSAGES";
const ADD_MESSAGE = "ADD_MESSAGE";
const SEARCH_USERS = "SEARCH_USERS";